### Create common area
POST {{host}}/CommonAreas
Accept: {{accept}}
Content-Type: multipart/form-data; boundary=BoundaryString

--BoundaryString
Content-Disposition: form-data; name="typeId"

5
--BoundaryString
Content-Disposition: form-data; name="startTime"

05:30:00
--BoundaryString
Content-Disposition: form-data; name="endTime"

00:00:00
--BoundaryString
Content-Disposition: form-data; name="timeInterval"

00:30:00
--BoundaryString
Content-Disposition: form-data; name="slots[0].name_en"

Playground 1
--BoundaryString
Content-Disposition: form-data; name="slots[0].name_ptbr"

Parque Infantil 1
--BoundaryString--

### Get all common areas
GET {{host}}/CommonAreas
Accept: {{accept}}

@Id = 3
@SlotId = 4
@Today = {{$datetime "YYYY-MM-DD"}}

### Get a common area
GET {{host}}/CommonAreas/{{Id}}
Accept: {{accept}}

### Get booking slots for the next 7 days
GET {{host}}/CommonAreas/{{Id}}/slot/{{SlotId}}/bookingSlots
Accept: {{accept}}

### Get booking slots for a specific date
GET {{host}}/CommonAreas/{{Id}}/slot/{{SlotId}}/date/{{Today}}/bookingSlots
Accept: {{accept}}

### Make a reservation
POST {{host}}/CommonAreas/{{Id}}/reservation
Accept: {{accept}}
Content-Type: multipart/form-data; boundary=BoundaryString

--BoundaryString
Content-Disposition: form-data; name="date"

{{Today}}
--BoundaryString
Content-Disposition: form-data; name="startAt"

10:00:00
--BoundaryString
Content-Disposition: form-data; name="slotId"

{{SlotId}}
--BoundaryString--