# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  tags:
    include:
    - '*'

pool: "Home Server"

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: build
    jobs:
    - job: run_build
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
  
  - stage: publish
    dependsOn: build
    jobs:
    - job: run_publish
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '$(solution)'
          arguments: '-c $(buildConfiguration) -o ./release /p:UseAppHost=false'
          zipAfterPublish: false
          modifyOutputPath: false
      - task: CopyFiles@2
        displayName: 'Copy ./release to staging directory'
        inputs:
          SourceFolder: './release'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/backend/release'
      - publish: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Publish dotnetapp'
        artifact: dotnetapp

  - stage: buildDockerImage
    dependsOn: publish
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
    - deployment: 
      displayName: "Deploy Docker Image"
      environment:
        name: "nextcondo-backend"
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: Docker@2
              displayName: 'Build docker image'
              inputs:
                containerRegistry: 'azure'
                repository: 'thejguih/nextcondoapi'
                command: 'build'
                Dockerfile: '**/Dockerfile'
                tags: 'beta-0.$(Build.BuildId)'
            - task: Docker@2
              displayName: 'Publish image to docker-hub'
              inputs:
                containerRegistry: 'azure'
                repository: 'thejguih/nextcondoapi'
                command: 'push'
                tags: |
                  $(Build.SourceBranchName)
                  latest
            - script: |
                docker rmi thejguih/nextcondoapi:$(Build.SourceBranchName)
              displayName: "Remove image $(Build.SourceBranchName) from host"
            - script: |
                docker rmi thejguih/nextcondoapi:latest
              displayName: "Remove image latest from host"