# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: "Home Server"

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  # - stage: build
  #   jobs:
  #   - job: run_build
  #     pool: "Home Server"
  #     steps:
  #     - task: UseDotNet@2
  #       inputs:
  #         packageType: 'sdk'
  #         version: '8.x'
  #     - task: DotNetCoreCLI@2
  #       displayName: 'Build dotnet API'
  #       inputs:
  #         command: 'build'
  #         projects: '*.csproj'
  #         arguments: '-c $(buildConfiguration)'
  #     - task: DotNetCoreCLI@2
  #       displayName: 'Publish dotnet API'
  #       inputs:
  #         command: 'publish'
  #         publishWebProjects: false
  #         projects: '*.csproj'
  #         arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) /p:UseAppHost=false'
  #         zipAfterPublish: false
  #         modifyOutputPath: false
  #     - script: |
  #         $(Agent.ToolsDirectory)/dotnet ef migrations bundle -o $(Build.ArtifactStagingDirectory)/bundle
  #     - publish: '$(Build.ArtifactStagingDirectory)'
  #       displayName: 'Publish NextCondo .Net API'
  #       artifact: nextcondoapi

  - stage: buildDockerImage
    jobs:
    - job: run_buildDockerImage
      pool: "Home Server"
      steps:
      - task: Docker@2
        displayName: 'Build docker image'
        inputs:
          containerRegistry: 'azure'
          command: 'build'
          Dockerfile: '**/Dockerfile'
          tags: 'beta-0.$(Build.BuildId)'
      # - task: Docker@2
      #   displayName: 'Publish image to docker-hub'
      #   inputs:
      #     containerRegistry: 'azure'
      #     repository: 'thejguih/nextcondo'
      #     command: 'push'
      #     tags: 'beta-0.$(Build.BuildId)'
      # - script: |
      #     docker rmi thejguih/nextcondo:beta-0.$(Build.BuildId)
      #   displayName: "Remove image from host"