# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  tags:
    include:
    - '*'

pool: "Home Server"

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: build
    jobs:
    - job:
      displayName: "Build dotnetapp"
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
  
  - stage: publish
    dependsOn: build
    jobs:
    - job:
      displayName: "Publish dotneapp"
      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '$(solution)'
          arguments: '-c $(buildConfiguration) -o $(System.DefaultWorkingDirectory)/release /p:UseAppHost=false'
          zipAfterPublish: false
          modifyOutputPath: false
      - script: |
          dotnet ef migrations bundle -o $(System.DefaultWorkingDirectory)/release/bundle
        displayName: "Create migrations bundle"
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/release'
          artifact: 'dotnetapp'
          publishLocation: 'pipeline'

  - stage: deploy
    dependsOn: publish
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
    - deployment: 
      displayName: "Deploy docker image"
      environment:
        name: "nextcondo-backend"
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'dotnetapp'
                targetPath: '$(System.DefaultWorkingDirectory)/release'
            - task: Docker@2
              displayName: 'Build docker image'
              inputs:
                containerRegistry: 'azure'
                repository: 'thejguih/nextcondoapi'
                command: 'build'
                Dockerfile: '**/Dockerfile'
                tags: |
                  $(Build.SourceBranchName)
                  latest
            - task: Docker@2
              displayName: 'Publish image to docker-hub'
              inputs:
                containerRegistry: 'azure'
                repository: 'thejguih/nextcondoapi'
                command: 'push'
                tags: |
                  $(Build.SourceBranchName)
                  latest
            - script: |
                docker rmi thejguih/nextcondoapi:$(Build.SourceBranchName)
              displayName: "Remove image $(Build.SourceBranchName) from host"
            - script: |
                docker rmi thejguih/nextcondoapi:latest
              displayName: "Remove image latest from host"