# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: "Home Server"

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: buildDockerImage
    jobs:
    - job: run_buildDockerImage
      pool: "Home Server"
      steps:
      - task: Docker@2
        displayName: 'Build docker image'
        inputs:
          containerRegistry: 'azure'
          repository: 'thejguih/nextcondoapi'
          command: 'build'
          Dockerfile: '**/Dockerfile'
          tags: 'beta-0.$(Build.BuildId)'
      - task: Docker@2
        displayName: 'Publish image to docker-hub'
        inputs:
          containerRegistry: 'azure'
          repository: 'thejguih/nextcondoapi'
          command: 'push'
          tags: 'beta-0.$(Build.BuildId)'
      - script: |
          docker rmi thejguih/nextcondoapi:beta-0.$(Build.BuildId)
        displayName: "Remove image from host"