# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  tags:
    include:
      - "*"

pool: "Home Server"

stages:
  - stage: build
    jobs:
      - job:
        displayName: "Build dotnetapp"
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: "build"

  - stage: apply_migrations
    dependsOn: build
    jobs:
      - job:
        displayName: "Apply migrations"
        steps:
          - script: |
              dotnet ef database update --project App
            displayName: "Applying migrations to test database"

  - stage: test
    dependsOn: apply_migrations
    jobs:
      - job:
        displayName: "Test dotnetapp"
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: "test"
              testRunTitle: "Unit and Integration Tests"

  - stage: publish
    dependsOn: test
    jobs:
      - job:
        displayName: "Publish dotnetapp"
        steps:
          - script: |
              dotnet ef migrations bundle \
                -o $(System.DefaultWorkingDirectory)/App/release/bundle \
                --force \
                --no-build \
                -r linux-x64 \
                --project App
          - task: DotNetCoreCLI@2
            inputs:
              command: 'publish'
              projects: App
              publishWebProjects: true
              arguments: '-c Release -o $(System.DefaultWorkingDirectory)/App/release /p:UseAppHost=false'
              zipAfterPublish: false
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/App/release'
              artifact: 'dotnetapp'
              publishLocation: 'pipeline'

  - stage: deploy
    dependsOn: test
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
      - deployment:
        displayName: "Deploy docker image"
        environment:
          name: "nextcondo-backend"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'current'
                    artifactName: 'dotnetapp'
                    targetPath: '$(System.DefaultWorkingDirectory)/App/release'
                - task: Docker@2
                  displayName: "Build docker image"
                  inputs:
                    containerRegistry: "azure"
                    repository: "thejguih/nextcondoapi"
                    command: "build"
                    Dockerfile: "App/Dockerfile"
                    buildContext: "App"
                    tags: |
                      $(Build.SourceBranchName)
                      latest
                - task: Docker@2
                  displayName: "Publish image to docker-hub"
                  inputs:
                    containerRegistry: "azure"
                    repository: "thejguih/nextcondoapi"
                    command: "push"
                    tags: |
                      $(Build.SourceBranchName)
                      latest
                - script: |
                    docker rmi thejguih/nextcondoapi:$(Build.SourceBranchName)
                  displayName: "Remove image $(Build.SourceBranchName) from host"
