FROM mcr.microsoft.com/dotnet/sdk:8.0 as build

WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY *.csproj .
RUN dotnet restore

# copy everything else and build app
COPY . ./
RUN dotnet publish -c release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 as runtime

WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT [ "dotnet", "simplify-condo-api.dll" ]