services:
  nextcondo-backend: 
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8080:8080
    depends_on:
      - nextcondo-postgres
    environment:
      DB_USER: nextcondo
      DB_PASSWORD: nextcondo
      DB_DATABASE: nextcondo
    networks:
      - nextcondotest

  nextcondo-postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: nextcondo
      POSTGRES_PASSWORD: nextcondo
      POSTGRES_DB: nextcondo
    networks:
      - nextcondotest

networks: 
  nextcondotest:
    external: true